pipeline {
  agent any
  stages {	
	stage('Maven Compile'){
		steps{
			echo 'Project compile stage' 
			cd another-maven-project
			bat label: 'Compilation running', script: '''mvn compile'''
	       	}
	}
	
	stage('Unit Test') {
	   steps {
			echo 'Project Testing stage'
		   	cd another-maven-project
			bat label: 'Test running', script: '''mvn test'''
	       
       		}
   	}

	stage('Jacoco Coverage Report') {
        	steps{
            		jacoco()
		}
	}
       
       stage('SonarQube'){
		steps{
				cd another-maven-project
				bat label: '', script: '''mvn sonar:sonar \
				-Dsonar.host.url=http://localhost:9000 \
				-Dsonar.login=2f036ae6363b4adf98c05726fd18efdaab28b123'''
			}
   		}
	
	stage('Maven Package'){
		steps{
			echo 'Project packaging stage'
			cd another-maven-project
			bat label: 'Project packaging', script: '''mvn package'''
		}
	} 		
    
  }
}
